"""empty message

Revision ID: 582c795c02e9
Revises: 
Create Date: 2024-08-02 13:43:02.420934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582c795c02e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('generated_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_content')
    # ### end Alembic commands ###
